site_name: Bhagyaj

plugins:
  - blogging:
      dirs:
        - blog 
  - search
  - tags

nav: 
  - index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


theme:
  name: material
  features:
    - tabs
  palette:
    primary: green
    accent: yellow

  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4


        name: Switch to Light mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to Dark mode

site_url: https://blog.bhagyaj.tech